# Aula 3 - Leitura de dados e Métodos úteis

Na aula de hoje, vamos explorar os seguintes tópicos em Python:

- 1) Leitura de dados (read_csv, read_excel, read_clipboard)
- 2) Atributos interessantes
- 3) Métodos úteis (drop, rename, sort_values, sort_index, reset_index, max, min, mean, median, sum, cumsum, quantile, describe, value_counts, unique, nunique)
- 4) Algumas formas de filtrar os dados
- 5) Salvar dados (to_csv, to_excel, read_clipboard)

______________

### Objetivos

Apresentar as várias formas de como ler e salvar de dados; alguns métodos que nos permitem aprofundar no conhecimento dos nossos dados e como filtrá-los.
______________


### Habilidades a serem desenvolvidas nessa aula

Ao final da aula o aluno deve:

- Saber como ler um arquivo com o pandas (csv, excel, etc.), criando DataFrames;
- Como salvar esses dados em um arquivo
- Como utilizar atributos e métodos mais importantes
- Como filtrar dados com operadores lógicos
- Deep dive nos dados

____
____
____

## Titanic

O arquivo que usaremos hoje é relativo ao Titanic! Essa é uma das bases mais famosas de ciência de dados. Você pode saber mais sobre estes dados [clicando aqui!](https://www.kaggle.com/c/titanic)

<center>
<img src=https://medias.revistaoeste.com/qa-staging/wp-content/uploads/2023/06/titanic-onde-esta-mapa-wikimedia.png width=700>
</center>

## Leitura de dados
[Documentação](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

| Data | Reader | Writer|
|------|--------|-------|
| CSV	| read_csv | to_csv |
| JSON	| read_json | to_json |
| HTML	| read_html | to_html |
| XML	| read_xml | to_xml |
| Local clipboard |	read_clipboard | to_clipboard
| MS Excel	|read_excel	| to_excel |
| OpenDocument|	read_excel	| |
| HDF5 |	read_hdf |	to_hdf |
| Parquet | read_parquet | to_parquet |
| SAS	|read_sas	| |
| SPSS	|read_spss	| |
| Python Pickle |	read_pickle | to_pickle| 
| SQL	|read_sql|	to_sql |
| Google BigQuery|	read_gbq | to_gbq |

### `.read_csv()`

In [3]:
# lê dataframe do arquivo titanic.csv 
import pandas as pd
df = pd.read_csv("data/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Agora que temos uma base mais complexa, vamos aproveitar para ver agora algumas outras funcionalidades do Pandas!

## Atributos
Atributos são as propriedades de um objeto, no caso um df.

### `.shape`
Retorna uma tupla com a quantidade de linhas e colunas do df. Esse na verdade é um atributo do df.

In [4]:
df.shape

(891, 12)

### `.size`
Retorna a quantidade de elementos do df. Também pode ser obtido pela multiplicação 
$$df.shape[0]*df.shape[1]$$

In [5]:
df.size

10692

### `.columns`
Retorna o nome das colunas e pode ser usado para renomear as colunas

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### `.index`
Retorna o index do df

In [ ]:
df.index

RangeIndex(start=0, stop=891, step=1)

### `.dtypes`

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

O pandas tenta reconhecer automaticamente os tipos das colunas.

## Métodos
Métodos são as ações que um objeto pode realizar.
O pandas possui alguns métodos para entendermos melhor a estrutura dos dados:

### `.head()` e `.tail()`
`.head()` retorna as primeiras linhas do df e `.tail()` retorna as últimas.

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [11]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### `.info()`
Fornece a quantidade de valores não nulos, o tipo de cada coluna e uso de memória.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### `.describe()`
`.describe(include='all')` descreve **estatísticas básicas** sobre todas as colunas, inclusive as que são objetos como strings e timestamp. Nesse caso, *top* representará o valor mais comum enquanto *freq* será a frequência em que apareceu esse valor.

Esse método é utilizado para gerar um resumo estatístico das colunas numéricas de um DataFrame. Por padrão, ele calcula automaticamente os três principais quartis (25%, 50% e 75%), que dividem os dados em quatro partes iguais

- 25% (Primeiro Quartil - Q1): Indica que 25% dos valores são menores ou iguais a esse número.
- 50% (Segundo Quartil ou Mediana): O valor central que divide o conjunto de dados ao meio.
- 75% (Terceiro Quartil - Q3): Indica que 75% dos valores estão abaixo desse número e 25% acima.

Se você precisar de outros quantis (como decis ou percentis específicos), pode usar o parâmetro percentiles: 

```python
# Exemplo para obter quartis personalizados e outros percentis
df.describe(percentiles=[.1, .25, .5, .75, .9])
```

Link para a [documentação](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html).

<center>
<img src="quartis.png" width=400>
</center>

In [13]:
# repare que nesse caso o próprio pandas fez o trabalho de reconhecer quais colunas são as numéricas
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#rogerio

In [14]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,1601,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

Ao carregar o dataset do Titanic, você notará que o Pandas identifica as colunas `PassengerId` e `Survived` como
  números inteiros (`int64`). Tecnicamente, isso está correto (elas contêm apenas números), mas do ponto de vista de
  Análise de Dados, essa classificação é semanticamente errada:

1. `PassengerId` (Identificador Único)
   * O que o Pandas vê: Uma sequência numérica crescente (1, 2, 3...).
   * O que realmente é: Uma variável qualitativa nominal. Esse número serve apenas como um "rótulo" ou "nome" para
     o passageiro.
   * Por que o int é ruim aqui? Não faz sentido matemático tirar a média dos IDs, somá-los ou calcular o desvio
     padrão. Tratá-los como números pode gerar gráficos estatísticos sem sentido (como um histograma de IDs).

2. `Survived`
   * O que o Pandas vê: Apenas zeros (0) e uns (1).
   * O que realmente é: Uma variável qualitativa binária (categórica/booleana). 
       * 0 representa "Não sobreviveu"
       * 1 representa "Sobreviveu"
   * Por que o int é enganoso aqui? Embora possamos tirar a média para saber a taxa de sobrevivência, o dado em si
     não é uma contagem ou medida, mas sim uma classificação. Em modelos de Machine Learning, é fundamental
     garantir que o algoritmo entenda que isso é uma categoria (classe) e não um valor escalar.


> O Pandas infere tipos baseando-se no formato do dado, mas ele não conhece o contexto do negócio. Como analistas,
  nosso papel é converter essas colunas para tipos adequados, como object ou category, logo após a leitura dos
  dados e é ai que entra o `.astype()`:

### `.astype()`
Converte o tipo da coluna.

1. Tipos de Dados Numéricos

    - 'int', 'int32', 'int64': Converte para números inteiros.
    - 'float', 'float32', 'float64': Converte para números de ponto flutuante.
    - 'uint8' a 'uint64': Inteiros sem sinal (positivos). 

2. Tipos de Dados de Texto e Objeto

    - 'str' ou 'string': Converte para texto (string). Muito usado para colunas que foram lidas incorretamente.
    - 'object': Converte para o tipo objeto genérico do pandas. 

3. Tipos Lógicos

    - 'bool': Converte para booleano (True/False). 

4. Datas e Tempo

    - 'datetime64[ns]': Converte para data e hora.
    - 'timedelta64[ns]': Converte para diferenças de tempo. 

5. Tipos Específicos do Pandas (Alta Performance)

    - 'category': Converte para dados categóricos. Essencial para otimização de memória e melhoria de desempenho quando uma coluna tem poucos valores únicos repetidos

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [17]:
# Converta as colunas 'PassengerId', 'Pclass' e 'Survived' para seus formatos respectivos
df[['PassengerId', 'Pclass']] = df[['PassengerId', 'Pclass']].astype("string")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    string
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    string
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(3), object(5), string(2)
memory usage: 83.7+ KB

In [18]:
df[["Survived"]] = df[["Survived"]].astype('bool')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    string
 1   Survived     891 non-null    bool
 2   Pclass       891 non-null    string
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: bool(1), float64(2), int64(2), object(5), string(2)
memory usage: 77.6+ KB

Outros exemplos comuns:

CEP e CPF: Ambos são feitos de números, mas ninguém soma dois CEPs para obter um terceiro endereço. Eles são textos disfarçados de números!

### `.value_counts()`
Traz a contagem de elementos pra cada valor distinto da coluna em que está sendo aplicado.

In [19]:
df.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: Int64

In [20]:
df.Pclass.value_counts(normalize=True)

Pclass
3    0.551066
1    0.242424
2     0.20651
Name: proportion, dtype: Float64

### `.unique()`
Retorna quem são os valores únicos da sua coluna. Equivalente ao DISTINCT column no SQL

In [21]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [22]:
df["Pclass"].unique()

<StringArray>
['3', '1', '2']
Length: 3, dtype: string

### `nunique()`
Retorna a quantidade de valores únicos da sua coluna. Equivalente ao COUNT (DISTINCT column) no SQL

In [23]:
df["Pclass"].nunique()

3

In [24]:
df["Ticket"].nunique()

681

### `.rename()`
Com esse método é possível renomear tanto o nome das colunas quanto o índice alterando o parâmetro axis. É um dos métodos que aceita o parâmetro `inplace`.

In [26]:
# vamos criar uma cópia do df
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
df.rename(columns={"SibSp": "SiblingSpouse", "Parch": "ParentsChildren"}, inplace=True)

In [30]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Ticket,Fare,Cabin,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `.drop()`
Permite deletar linhas (`axis=0`) ou colunas (`axis=1`) inteiras dependendo do parâmetro `axis`. É um dos métodos que aceita o parâmetro `inplace`.

In [33]:
df.drop(columns=["Ticket", "Cabin"], inplace=True)

In [34]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q

### `.sort_values()`
O método é utilizado para ordenar os dados baseado em uma ou mais colunas. Para retornar a ordem reversa utilize o argumento `ascending=True`. É um dos métodos que aceita o parâmetro `inplace`.

In [40]:
df.sort_values(by=["Pclass", "Fare"]).tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
201,202,False,3,"Sage, Mr. Frederick",male,NaN,8,2,69.55,S
324,325,False,3,"Sage, Mr. George John Jr",male,NaN,8,2,69.55,S
792,793,False,3,"Sage, Miss. Stella Anna",female,NaN,8,2,69.55,S
846,847,False,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,69.55,S
863,864,False,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,69.55,S

Para ordernar colunas distintas em ordens distintas é preciso passar uma lista booleana para o argumento ascending com a mesma quantidade de colunas.

In [41]:
df.sort_values(by=["Pclass", "Fare"], ascending=[True, False])

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,512.3292,C
737,738,True,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,512.3292,C
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,263.0000,S
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
...,...,...,...,...,...,...,...,...,...,...
378,379,False,3,"Betros, Mr. Tannous",male,20.0,0,0,4.0125,C
179,180,False,3,"Leonard, Mr. Lionel",male,36.0,0,0,0.0000,S
271,272,True,3,"Tornquist, Mr. William Henry",male,25.0,0,0,0.0000,S
302,303,False,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,0.0000,S
597,598,False,3,"Johnson, Mr. Alfred",male,49.0,0,0,0.0000,S

###  `.set_index()` e `.reset_index()`
Como vimos na aula anterior, o `.set_index()` é utilizado para considerar uma das colunas do df como index enquanto o `.reset_index()` enumera as linhas reseta o index substituindo seus valores por um range numérico que vai de de 0 até o tamanho do df -1, convertendo o antigo index em uma coluna.

___________________
___________________
**Exercício:** <br>

a) Dropar as colunas SibSp, Parch, Embarked, Cabin. <br>
b) Deixe o nome das colunas todas em minúsculo e seguindo o padrão da documentação python de deixar palavras separadas por _ . Exemplo: PassengerId -> passenger_id <br>
c) Ordene por idade (decrescente) e nome (crescente)

___________________
___________________

# voltamos às 20:43

## Filtros

Podemos **fazer filtros** muito facilmente

Basta explicitarmos **condições sobre os valores das colunas**, e utilizar isso como indexador do dataframe!

<center>
<img src="filtro_1.png" text="https://swdevnotes.com/python/2021/how-to-filter-a-pandas-dataframe/" width=700>

<img src="filtro_2.png" text="https://swdevnotes.com/python/2021/how-to-filter-a-pandas-dataframe/" width=700>
</center>

Filtros aceitos pelo pandas:
<center>
<img src="filtros.png" text="https://swdevnotes.com/python/2021/how-to-filter-a-pandas-dataframe/" width=500>
</center>

In [43]:
# Filtre o df para 'Fare' maior que 260
mask = df.Fare > 260
mask

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [44]:
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,263.0000,S
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
438,439,False,1,"Fortune, Mr. Mark",male,64.0,1,4,263.0000,S
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,512.3292,C
737,738,True,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,512.3292,C
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

In [ ]:
df[df.Fare > 260]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,263.0000,S
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
438,439,False,1,"Fortune, Mr. Mark",male,64.0,1,4,263.0000,S
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,512.3292,C
737,738,True,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,512.3292,C
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

In [46]:
df[df['Fare'] > 260]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,263.0000,S
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
438,439,False,1,"Fortune, Mr. Mark",male,64.0,1,4,263.0000,S
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,512.3292,C
737,738,True,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,512.3292,C
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

In [48]:
df.Fare

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [49]:
df["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [50]:
df[["Fare"]]

        Fare
0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
..       ...
886  13.0000
887  30.0000
888  23.4500
889  30.0000
890   7.7500

[891 rows x 1 columns]

Se quisermos fazer filtros mais complexos (filtros compostos, em mais de uma coluna), podemos fazer **conjunções entre filtros**, utilizando os **operadores lógicos de conjunção**. Aqui é obrigatório o uso dos parênteses para que os filtros sejam aplicados corretamente.

Obs.: temos os seguintes operadores lógicos:

- `&`     - corresponde ao "and"
- `|`     - corresponde ao "or"
- `~`     - corresponde ao "not"

In [55]:
(df['Fare'] >= 260) & (df['Sex'] == 'female')

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [ ]:
2+(2*3)

In [56]:
# filtar df para Fare >= 260 e Sex == 'female'
df[(df['Fare'] >= 260) & (df['Sex'] == 'female') & (df['Age']>=23)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S

In [54]:
# filtar df para Fare >= 260 ou Sex = female
df[(df['Fare'] >= 260) | (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
8,9,True,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,11.1333,S
9,10,True,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,30.0708,C
...,...,...,...,...,...,...,...,...,...,...
880,881,True,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,26.0000,S
882,883,False,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,10.5167,S
885,886,False,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,29.1250,Q
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S

In [59]:
# Podemos criar um novo df diretamento do filtro
df_mulheres_ricas = df[(df["Fare"]>260) & (df["Sex"] == 'female')]
df_mulheres_ricas

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

## Atenção: 

> **O uso de parênteses ao combinar condições no Pandas (como `&`, `|`, `~`) é obrigatório.**

Isso acontece por causa da precedência de operadores na linguagem Python:

1. Os operadores bitwise (`&`, `|`) têm uma precedência maior do que os operadores de comparação (`>=`, `==`, `<`).

2. Sem os parênteses, o Python tentaria executar o `&` primeiro. No seu exemplo, ele tentaria fazer: `260 & df["Sex"]`, o que geraria um erro de tipo (`TypeError`), pois não faz sentido lógico.

O que acontece na prática:

* Com parênteses (Correto):

    `df[(df["Fare"] >= 260) & (df["Sex"] == 'female')]`
    1. Resolve (`df["Fare"] >= 260`) -> Gera uma Série de True/False.
    2. Resolve (`df["Sex"] == 'female'`) -> Gera outra Série de True/False.
    3. O `&` compara as duas Séries e retorna o filtro final.

* Sem parênteses (Erro):

    `df[df["Fare"] >= 260 & df["Sex"] == 'female']`

Dica de Senior: Mesmo quando você tem apenas uma condição, como df`[df["Age"] > 30]`, os parênteses não são obrigatórios, mas ao usar qualquer
operador de combinação (`&`, `|`, `~`), coloque sempre parênteses em cada condição individual para evitar erros.

In [58]:
# df[df["Fare"] >= 260 & df["Sex"] == 'female']

### Aprofundamento: Outras formas de filtrar
#### `.query()`
Se utilizar aspas simples para escrever a query, dentro dela utilize aspas duplas e vice-versa.

In [62]:
df.query("Fare > 260 and Sex=='female'")
df.query("Fare > 260 & Sex=='female'")
df.query('Fare > 260 & Sex=="female"')

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

O método query também permite usarmos uma variável do workspace atual:

In [ ]:
fare_threshold = 260
gender = 'female'
df.query("Fare > @fare_threshold & Sex==@gender")

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

In [71]:
# df.query("Fare > @fare_threshold & Sex like @gender")

#### `.isin()`
Usado para filtrar Strings e valores numéricos. Passamos os valores dentro de uma lista.

In [64]:
df[df.Name == 'Newell, Miss. Madeleine']

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.275,C

In [67]:
# Vamos filtrar o df para os nomes: ['Newell, Miss. Madeleine', 'Fleming, Miss. Margaret']
df[df.Name.isin(['Newell, Miss. Madeleine', 'Fleming, Miss. Margaret'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.2750,C
306,307,True,1,"Fleming, Miss. Margaret",female,NaN,0,0,110.8833,C

In [69]:
# Agora suponha que queremos apenas os passageiros com idade 1 ou 2
df[df.Age.isin([1,15])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
22,23,True,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,8.0292,Q
164,165,False,3,"Panula, Master. Eino Viljami",male,1.0,4,1,39.6875,S
172,173,True,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,11.1333,S
183,184,True,2,"Becker, Master. Richard F",male,1.0,2,1,39.0000,S
352,353,False,3,"Elias, Mr. Tannous",male,15.0,1,1,7.2292,C
381,382,True,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,15.7417,C
386,387,False,3,"Goodwin, Master. Sidney Leonard",male,1.0,5,2,46.9000,S
689,690,True,1,"Madill, Miss. Georgette Alexandra",female,15.0,0,1,211.3375,S
788,789,True,3,"Dean, Master. Bertram Vere",male,1.0,1,2,20.5750,S
827,828,True,2,"Mallet, Master. Andre",male,1.0,0,2,37.0042,C
830,831,True,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,14.4542,C
875,876,True,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,7.2250,C

#### `.str.contains()`
O `.str.contains()` busca um padrão de texto dentro das strings.

In [72]:
# E se quisermos saber quais passageiros eram da mesma família com sobrenome 'Newell'?
df[df.Name.str.contains('Newell')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.275,C
393,394,True,1,"Newell, Miss. Marjorie",female,23.0,1,0,113.275,C
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,113.275,C

In [77]:
df[df.Name.str.contains('well')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
78,79,True,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,29.000,S
215,216,True,1,"Newell, Miss. Madeleine",female,31.00,1,0,113.275,C
323,324,True,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.00,1,1,29.000,S
339,340,False,1,"Blackwell, Mr. Stephen Weart",male,45.00,0,0,35.500,S
393,394,True,1,"Newell, Miss. Marjorie",female,23.00,1,0,113.275,C
564,565,False,3,"Meanwell, Miss. (Marion Ogden)",female,NaN,0,0,8.050,S
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,113.275,C
889,890,True,1,"Behr, Mr. Karl Howell",male,26.00,0,0,30.000,C

In [73]:
# E se quisermos saber quais passageiros eram da família com sobrenome 'Newell' ou 'Fleming'?
df[df.Name.str.contains('Newell|Fleming')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.2750,C
306,307,True,1,"Fleming, Miss. Margaret",female,NaN,0,0,110.8833,C
393,394,True,1,"Newell, Miss. Marjorie",female,23.0,1,0,113.2750,C
413,414,False,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,0.0000,S
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,113.2750,C

#### `.str.startswith()`
Já nesse método não estamos buscando um padrão em qualquer local da string, queremos apenas aqueles que começam com esse valor.

In [74]:
df[df['Name'].str.startswith('Newell')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.275,C
393,394,True,1,"Newell, Miss. Marjorie",female,23.0,1,0,113.275,C
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,113.275,C

In [75]:
df[df['Name'].str.startswith('newell')]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SiblingSpouse, ParentsChildren, Fare, Embarked]
Index: []

In [76]:
df[df['Name'].str.startswith('New')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
136,137,True,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,26.2833,S
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,113.2750,C
393,394,True,1,"Newell, Miss. Marjorie",female,23.0,1,0,113.2750,C
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,113.2750,C

_____________
_____________
**Exercício:** Quantas crianças com menos de 5 anos sobreviveram?

______________
______________

## Salvando dados
Podemos salvar os dados em vários formatos como csv, xlsx, parquet...

#### `.to_csv()`

In [79]:
df_mulheres_ricas

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingSpouse,ParentsChildren,Fare,Embarked
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,512.3292,C
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,262.3750,C
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000,S
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,262.3750,C

In [ ]:
# salvando em csv
df_mulheres_ricas.to_csv("mulheres_ricas.csv", index=False)

______
______

# Material de Aprofundamento

## Extração de dados
### `.read_clipboard()`
Nesse caso eu precisei instalar a biblioteca `PyQt5` com `!pip install PyQt5`.
Dê CRTL+C nessa matriz: <br> <br>

  A B C

x 1 4 p

y 2 5 q

z 3 6 r
df_clipboard = pd.read_clipboard()
df_clipboard

###  `.memory_usage()`
Retorna a quantidade de memória utilizada por cada coluna em bytes.

In [ ]:
df.memory_usage()

#### `.between()`
Usado apenas com valores numéricos ao passar o valor inicial e final dentro dos parênteses.

In [ ]:
df[df['Fare'].between(100,120)].head(2)

____
______

## Exercícios

1. Considere a existência de três tabelas distintas:
* customer.csv : Possui a informação dos clientes em duas colunas: customer id  customer name
* products.csv : Contém informação dos produtos vendidos pela empresa em três colunas - p_id (product id), product (name) e price
* sales.csv : Contém informações das vendas realizadas em seis colunas - sale_id, c_id (customer id), p_id (product_id), qty (quantity sold), store (name)


Tome algum tempo para usar os métodos apresentados em aula para entender cada uma das bases antes de começar.

Agora conhecendo um pouco melhor as bases responda:

a) Quais foram os produtos vendidos? Responda usando um dos métodos apresentados.

b) E os não vendidos?

c) A área de produtos gostaria de saber quais foram as cinco maiores vendas, suas quantidades e loja responsável. Salve essas vendas em um arquivo csv com as informações que área precisa.

d) Liste a quantidade vendida de cada produto. Utilize um loop for para isso.

e) Liste a quantidade vendida de cada loja.

**Desafio:**

f) Liste a quantidade vendida de cada produto por loja.

## Referências
[Leitura de dados](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) <br>
[Seleção dos dados](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html) <br>
[Lista de atributos e métodos](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.html)

## [Avaliação anônima](https://forms.gle/tShxhxNYhvi6ZmQm8)