# 🎯Aula 6 - Tratamento de dados: Duplicados, Constantes e Nulos🎯

**Situação Problema:**

Suponha que você é um analista de dados contratado por uma empresa de e-commerce para analisar as vendas. Eles te fornecem um conjunto de dados com as seguintes colunas:

- *InvoiceNo:* Número da fatura
- *StockCode:* Código do produto
- *Description:* Descrição do produto
- *Quantity:* Quantidade vendida
- *InvoiceDate:* Data da fatura
- *UnitPrice:* Preço unitário do produto
- *CustomerID:* ID do cliente
- *Country:* País de onde veio a compra
- *PayMethod:* Método de pagamento
- *OrderStatus:* Se o pedido foi cancelado, entregue, aguardando pagamento ou em transporte

In [1]:
import pandas as pd
import numpy as np

In [3]:
df_CRM = pd.read_csv("data/data_CRM_more.csv")
df_CRM.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
0,536365,85123A,NaN,6,12/1/2010 8:26,2.55,17850.0,Brazil,1.0,3.0
1,536365,71053,NaN,6,12/1/2010 8:26,3.39,17850.0,Brazil,1.0,4.0
2,536365,84406B,NaN,8,12/1/2010 8:26,2.75,17850.0,Brazil,1.0,2.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,Brazil,1.0,2.0
4,536365,84029E,NaN,6,12/1/2010 8:26,NaN,17850.0,Brazil,2.0,5.0

In [4]:
df_CRM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  153304 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    514814 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   PayMethod    487718 non-null  float64
 9   OrderStatus  487718 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 41.3+ MB

In [12]:
df_CRM.describe(include='all').round(1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
count,541909,541909,153304,541909.0,541909,514814.0,406829.0,541909,487718.0,487718.0
unique,25900,4070,3810,NaN,23260,NaN,NaN,1,NaN,NaN
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,Brazil,NaN,NaN
freq,1114,2313,649,NaN,1114,NaN,NaN,541909,NaN,NaN
mean,NaN,NaN,NaN,9.6,NaN,4.4,15287.7,NaN,2.0,3.0
std,NaN,NaN,NaN,218.1,NaN,97.7,1713.6,NaN,0.8,1.4
min,NaN,NaN,NaN,-80995.0,NaN,-11062.1,12346.0,NaN,1.0,1.0
25%,NaN,NaN,NaN,1.0,NaN,1.2,13953.0,NaN,1.0,2.0
50%,NaN,NaN,NaN,3.0,NaN,2.1,15152.0,NaN,2.0,3.0
75%,NaN,NaN,NaN,10.0,NaN,4.1,16791.0,NaN,3.0,4.0
max,NaN,NaN,NaN,80995.0,NaN,38970.0,18287.0,NaN,3.0,5.0

Ao analisar os dados, você percebeu que o campo 
- `Description` está com aproximadamente 70% dos dados em branco
- `Country` está sempre com o mesmo valor `Brazil`
- Temos duplicado em `InvoiceNo`, mas uma mesma venda pode ter o mesmo `InvoiceNo`
- `Quantity` e `UnitPrice` tem valores negativos

O que isto poderia significar? Qual o impacto desses campos com valores atípicos para a análise?

Nesses casos de dados 'sujos', o que poderíamos fazer?

___________________
___________________

## Limpeza de Dados: Dados duplicados
### `.duplicated()` e `.drop_duplicates()`

O `.duplicated()` retorna uma máscara series booleana indicando se determinada linha possui duplicados ou não. Já o `.drop_duplicates()`, elimina as linhas duplicadas. <br>
Parâmetros do `.drop_duplicates()`:

   * `subset` -  seleciona colunas para serem utilizadas na comparação de linhas duplicadas
   * `keep` - {‘first’, ‘last’} (default ‘first’) Determina qual duplicado manter
   * `inplace` - (default False) Se False retorna uma cópia do df com as alterações, se True faz as modificações no próprio df

In [13]:
df_CRM.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Length: 541909, dtype: bool

In [14]:
df_CRM.duplicated().sum()

158

In [23]:
df_CRM[df_CRM.duplicated()].sort_values(by=["InvoiceNo", 'StockCode'])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
4122,536749,21415,NaN,2,12/2/2010 13:49,2.10,17976.0,Brazil,2.0,3.0
4156,536749,22174,NaN,2,12/2/2010 13:49,1.65,17976.0,Brazil,2.0,4.0
4627,536796,22585,NaN,1,12/2/2010 15:46,1.25,15574.0,Brazil,2.0,5.0
5732,536874,22910,NaN,1,12/3/2010 11:35,2.95,16891.0,Brazil,3.0,3.0
7735,537051,85175,NaN,32,12/5/2010 11:12,0.42,15708.0,Brazil,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...
522464,580399,21111,NaN,1,12/4/2011 11:45,1.25,13471.0,Brazil,1.0,1.0
522560,580402,22065,CHRISTMAS PUDDING TRINKET POT,10,12/4/2011 11:55,0.39,13536.0,Brazil,1.0,3.0
523803,580520,23295,NaN,1,12/4/2011 14:55,0.83,13521.0,Brazil,1.0,1.0
531204,580908,22139,RETROSPOT TEA SET CERAMIC 11 PC,1,12/6/2011 13:20,4.95,16495.0,Brazil,1.0,3.0
531654,580958,20781,NaN,1,12/6/2011 14:30,1.95,17266.0,Brazil,2.0,5.0

In [22]:
df_CRM[(df_CRM["InvoiceNo"]=='536749') & (df_CRM["StockCode"]=='21415')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
4118,536749,21415,NaN,2,12/2/2010 13:49,2.1,17976.0,Brazil,2.0,3.0
4122,536749,21415,NaN,2,12/2/2010 13:49,2.1,17976.0,Brazil,2.0,3.0
4147,536749,21415,NaN,2,12/2/2010 13:49,2.1,17976.0,Brazil,1.0,5.0

In [36]:
df_CRM[df_CRM.duplicated(subset=["InvoiceNo", 'StockCode'])].sort_values(by=["InvoiceNo", 'StockCode']).iloc[110:120]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
3565,536637,22945,NaN,12,12/2/2010 11:35,0.85,18041.0,Brazil,1.0,1.0
3702,536643,85099B,NaN,3,12/2/2010 11:57,1.95,14390.0,Brazil,1.0,5.0
4000,536742,20978,NaN,3,12/2/2010 13:14,1.25,16916.0,Brazil,3.0,5.0
4004,536742,22553,NaN,1,12/2/2010 13:14,1.65,16916.0,Brazil,3.0,2.0
4122,536749,21415,NaN,2,12/2/2010 13:49,2.10,17976.0,Brazil,2.0,3.0
4147,536749,21415,NaN,2,12/2/2010 13:49,2.10,17976.0,Brazil,1.0,5.0
4133,536749,22174,PHOTO CUBE,2,12/2/2010 13:49,1.65,17976.0,Brazil,1.0,2.0
4156,536749,22174,NaN,2,12/2/2010 13:49,1.65,17976.0,Brazil,2.0,4.0
4137,536749,22371,NaN,2,12/2/2010 13:49,4.25,17976.0,Brazil,1.0,4.0
4158,536749,22371,NaN,1,12/2/2010 13:49,4.25,17976.0,Brazil,NaN,NaN

In [ ]:
# df_CRM[~df_CRM.duplicated()]
df_CRM.drop_duplicates()
# df_CRM.drop_duplicates(inplace=True)
df_CRM = df_CRM.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
0,536365,85123A,NaN,6,12/1/2010 8:26,2.55,17850.0,Brazil,1.0,3.0
1,536365,71053,NaN,6,12/1/2010 8:26,3.39,17850.0,Brazil,1.0,4.0
2,536365,84406B,NaN,8,12/1/2010 8:26,2.75,17850.0,Brazil,1.0,2.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,Brazil,1.0,2.0
4,536365,84029E,NaN,6,12/1/2010 8:26,NaN,17850.0,Brazil,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,NaN,12,12/9/2011 12:50,0.85,12680.0,Brazil,1.0,3.0
541905,581587,22899,NaN,6,12/9/2011 12:50,2.10,12680.0,Brazil,1.0,5.0
541906,581587,23254,NaN,4,12/9/2011 12:50,4.15,12680.0,Brazil,2.0,1.0
541907,581587,23255,NaN,4,12/9/2011 12:50,4.15,12680.0,Brazil,NaN,NaN
541908,581587,22138,NaN,3,12/9/2011 12:50,4.95,12680.0,Brazil,1.0,4.0

In [40]:
df_CRM.shape

(541909, 10)

In [41]:
print(df_CRM.shape)
df_CRM.drop_duplicates(inplace=True)
print(df_CRM.shape)

(541909, 10)
(541751, 10)

_____
_____

## Dados constantes

**Problema:**

Dados constantes em uma coluna (todas linhas possuem o mesmo valor) geralmente não agregam valor à análise. Eles não variam e, portanto, não contribuem para a diferenciação ou correlação com outras variáveis.

### Remoção com `.drop()`:

Para remover uma coluna de um DataFrame, usamos o método `.drop()`.

**Exemplo:** Remova a coluna `Country` do dataframe.

In [43]:
df_CRM.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PayMethod,OrderStatus
count,541751,541751,153282,541751.000000,541751,514658.000000,406671.000000,541751,487587.000000,487587.000000
unique,25900,4070,3810,NaN,23260,NaN,NaN,1,NaN,NaN
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,Brazil,NaN,NaN
freq,1114,2313,649,NaN,1114,NaN,NaN,541751,NaN,NaN
mean,NaN,NaN,NaN,9.554118,NaN,4.429948,15287.497422,NaN,2.000349,3.001821
std,NaN,NaN,NaN,218.112912,NaN,97.759554,1713.645571,NaN,0.816575,1.413445
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN,1.000000,1.000000
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13952.000000,NaN,1.000000,2.000000
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN,2.000000,3.000000
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN,3.000000,4.000000
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN,3.000000,5.000000

In [44]:
df_CRM["Country"].value_counts()

Country
Brazil    541751
Name: count, dtype: int64

In [45]:
df_CRM["Country"].nunique()

1

In [46]:
df_CRM["Country"].unique()

array(['Brazil'], dtype=object)

In [48]:
df_CRM.drop(columns=["Country"], inplace=True)

In [49]:
df_CRM.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'PayMethod', 'OrderStatus'],
      dtype='object')

_____
_____

## Dados Nulos

**Problema:**

Dados nulos podem ser problemáticos pois indicam a falta de informação, o que pode afetar a precisão dos modelos e análises. Exemplos de problemas associados são:

- **Distorsão de Estatísticas:** Dados nulos podem levar a cálculos incorretos de medidas estatísticas, como média e desvio padrão.
- **Comprometimento de Modelos:** Em modelos de Machine Learning, dados nulos podem causar erros ou levar a resultados imprecisos.
- **Perda de Informações:** A exclusão de linhas com dados nulos pode resultar na perda de dados valiosos.

#### Exemplo: Empresa de E-commerce - Análise de Churn (Cancelamento)
Imagine uma empresa de e-commerce que deseja entender por que os clientes cancelam suas assinaturas (churn). Eles têm uma base de dados de clientes e uma coluna chamada "motivo_cancelamento".

O Problema: A coluna "motivo_cancelamento" está com 70% dos campos nulos, porque muitos clientes cancelam pelo app sem preencher o formulário opcional.

A Ação Errada: O analista de dados, querendo uma base "limpa", decide deletar todas as linhas onde "motivo_cancelamento" é nulo (df.dropna()).

O Resultado (O Problema): 
- Viés de Seleção: A empresa ficou apenas com os clientes que escreveram um motivo (geralmente reclamações muito específicas ou raivosas), perdendo a representação dos clientes que saíram por motivos silenciosos (preço, concorrência, desinteresse).
- Análise Distorcida: A empresa concluiu que o problema era "qualidade do produto" (motivo mais comum nas respostas preenchidas), quando na verdade a maioria saiu por "preço alto" (motivo que não foi capturado).
- Prejuízo Financeiro: A empresa investiu em melhoria de produto, mas o churn continuou alto porque o problema real era o preço, que foi ocultado pela deleção dos dados nulos

#### Removendo dados nulos

Uma das possíveis soluções para tratamento de dados nulos é a sua completa remoção.

**Removendo colunas:**

Quando temos uma coluna com boa parte dos dados nulos (**Ex.:** `Description`), significa que não conseguiríamos tirar insights dessas colunas.

Além disso, modelos de machine learning e ferramentas de visualização de dados não precisam utilizar esses dados.

Portanto, podemos remover esses dados sem problemas.

##### `.isna() e isnull()`
retorna um df booleano indicando se existe um nulo naquela posição. `pd.isnull()` é um alias para `pd.isna()` dentro do python como podemos ver na <a href="https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/core/dtypes/missing.py#L109">documentação</a>. O pandas dataframe é baseado nos df do R, onde null e na tem sentidos distintos.

In [51]:
# Verificação do total e da porcentagem de dados nulos:
df_CRM.isna().sum()

InvoiceNo           0
StockCode           0
Description    388469
Quantity            0
InvoiceDate         0
UnitPrice       27093
CustomerID     135080
PayMethod       54164
OrderStatus     54164
dtype: int64

In [53]:
100*df_CRM.isna().mean()

InvoiceNo       0.000000
StockCode       0.000000
Description    71.706190
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       5.001006
CustomerID     24.933964
PayMethod       9.997951
OrderStatus     9.997951
dtype: float64

In [54]:
# Apagar os dados de Description, por ser praticamente vazio nos dados
df_CRM.drop(columns=["Description"], inplace=True)

In [55]:
100*df_CRM.isna().mean()

InvoiceNo       0.000000
StockCode       0.000000
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       5.001006
CustomerID     24.933964
PayMethod       9.997951
OrderStatus     9.997951
dtype: float64

**Removendo linhas nulas com `dropna()`:**

Às vezes algumas colunas de interese possuem vazios e fazem muita falta para compreensão dos dados. Por exemplo, no campo `CustomerID`, não temos 25% dos dados.

Podemos neste caso, remover os registros vazios, pois não sabemos se são clientes ou não.

In [57]:
# Remover registros nulos da coluna
df_CRM.dropna(subset=["CustomerID"], inplace=True)

In [58]:
#Verificação da porcentagem de dados nulos:
df_CRM.isna().mean()

InvoiceNo      0.000000
StockCode      0.000000
Quantity       0.000000
InvoiceDate    0.000000
UnitPrice      0.050149
CustomerID     0.000000
PayMethod      0.100167
OrderStatus    0.100167
dtype: float64

#### Estratégias para preenchimento de dados nulos:

Existem diversas estratégias para preencher dados nulos, entre elas, pode-se citar:

1. **Preenchimento com média, mediana ou moda**
- **Aplicação:** Recomendado para dados contínuos (média, mediana) e categóricos (moda).
- **Prós:**
  - Preserva a forma geral do conjunto de dados.
  - Rápido e eficiente para grandes conjuntos de dados.
- **Contras:**
  - Pode ser enganoso se a distribuição dos dados for assimétrica ou tiver outliers significativos.
  - Não leva em conta a possível correlação entre as variáveis.

##### `.fillna()`

preeche os valores nulos com valores especificados dentro do método. Esses valores podem tanto ser uma constante quanto aplicar técnicas como o backfill e o forward fill.

Parâmetros úteis:

   * `method {‘bfill’,‘ffill’, None}`, default None <br>
       Preenche os nas propagando o último valor válido para frente (ffill) ou utiliza próxima observação válida para preencher os nulos (bfill).
   * `limit`, default None <br>
       Quantidade máxima de nulos sequenciais a ser preenchido. 
   * `axis` {0 para ‘index’, 1 para ‘colunas’} <br>
       Eixo no qual se quer preencher os nulos
   * `inplace` {booleano}, default False

In [60]:
# Definir a média da coluna UnitPrice dos dados
media_preco = df_CRM["UnitPrice"].mean()
print(media_preco)

# Inputar dados nulos
df_CRM["UnitPrice"].fillna(media_preco, inplace=True)

df_CRM.isna().mean()

3.291269912523913

/tmp/ipykernel_309113/3720429718.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_CRM["UnitPrice"].fillna(media_preco, inplace=True)

InvoiceNo      0.000000
StockCode      0.000000
Quantity       0.000000
InvoiceDate    0.000000
UnitPrice      0.000000
CustomerID     0.000000
PayMethod      0.100167
OrderStatus    0.100167
dtype: float64

### Aprofundamento

2. **Preenchimento com Valores Anteriores ou Posteriores**
- **Aplicação:** Ideal para séries temporais ou dados onde a sequência é importante.
- Prós:
  - Mantém a sequência lógica nos dados, o que é crucial em séries temporais.
- Contras:
  - Pode introduzir viés se houver mudanças abruptas ou tendências nos dados.

In [ ]:
# Preenchendo dados faltantes na coluna UnitPrice com valores anteriores ('ffill')
df_CRM["UnitPrice"].fillna(method = "ffill")

In [ ]:
# Preenchendo dados faltantes na coluna UnitPrice com valores posteriores ('bfill')
df_CRM["UnitPrice"].fillna(method = "bfill")

3. **Métodos de Interpolação**
- **Aplicação:** Útil em séries temporais ou quando os dados seguem uma tendência.
- **Prós:**
  - Oferece um método mais sofisticado e adaptativo para estimar valores nulos.
- **Contras:**
  - Pode ser complexo de implementar e entender.

[Documentação](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.interpolate.html)

Principais parâmetros: `Series.interpolate(method='linear', order=None, axis=0, limit=None, inplace=False)`

In [ ]:
# preencher com dados interpolados (interpolação linear)
df_CRM["UnitPrice"].interpolate(method="linear")

In [ ]:
# preencher com dados interpolados (interpolação polinomial)
df_CRM["UnitPrice"].interpolate(method="polynomial", order=2)

4. Criar uma Categoria "Outros/Desconhecido": Transformar o nulo em um dado categórico para manter a linha na análise.
5. Manter como Nulo: Se o nulo for informativo, mantenha-o.

Sempre busque investigar a Causa: Por que é nulo? É "missing at random" ou "not at random"?

### Representação de Valores Ausentes em Conjuntos de Dados

Valores ausentes podem aparecer de diferentes formas, por isso é importante utilizar um formato consistente e bem documentado para uma manipulação limpa dos dados.

As representações comuns incluem:

- Células em branco: Entradas vazias em planilhas ou arquivos CSV.
- Valores especiais: Placeholders como "NA", "NaN", "NULL", "", "  " ou números como -999.
- Códigos ou sinalizadores: Rótulos como "MISSING" ou "UNKNOWN" para indicar tipos específicos de dados ausentes.

_________
_________

## Substituição de valores

### `.replace()`

substitui elementos dentro do df. É um dos métodos que aceita o parâmetro `inplace`.

Sabendo que:

In [65]:
metodos_pagamento = {
    1: 'Cartão de Crédito', 2: 'Cartão de Débito', 3: 'Transferência'
}
status_pedido = {
    1: 'aguardando pagamento', 2: 'pago', 3: 'em transporte', 4: 'entregue', 5: 'cancelado'
}

In [ ]:
# todas as colunas

df_CRM.replace(
    {1: "Cartão de Crédito"}
)

,InvoiceNo,StockCode,Quantity,InvoiceDate,UnitPrice,CustomerID,PayMethod,OrderStatus
0,536365,85123A,6,12/1/2010 8:26,2.55,17850.0,Cartão de Crédito,3.0
1,536365,71053,6,12/1/2010 8:26,3.39,17850.0,Cartão de Crédito,4.0
2,536365,84406B,8,12/1/2010 8:26,2.75,17850.0,Cartão de Crédito,2.0
3,536365,84029G,6,12/1/2010 8:26,3.39,17850.0,Cartão de Crédito,2.0
4,536365,84029E,6,12/1/2010 8:26,3.29127,17850.0,2.0,5.0
...,...,...,...,...,...,...,...,...
541904,581587,22613,12,12/9/2011 12:50,0.85,12680.0,Cartão de Crédito,3.0
541905,581587,22899,6,12/9/2011 12:50,2.1,12680.0,Cartão de Crédito,5.0
541906,581587,23254,4,12/9/2011 12:50,4.15,12680.0,2.0,Cartão de Crédito
541907,581587,23255,4,12/9/2011 12:50,4.15,12680.0,NaN,NaN
541908,581587,22138,3,12/9/2011 12:50,4.95,12680.0,Cartão de Crédito,4.0

In [63]:
# para apenas uma troca
df_CRM.PayMethod.replace(
    {1: "Cartão de Crédito", 2: "Cartão de Débito", 3: "Transferência"}
)

0         Cartão de Crédito
1         Cartão de Crédito
2         Cartão de Crédito
3         Cartão de Crédito
4          Cartão de Débito
                ...
541904    Cartão de Crédito
541905    Cartão de Crédito
541906     Cartão de Débito
541907                  NaN
541908    Cartão de Crédito
Name: PayMethod, Length: 406671, dtype: object

In [66]:
# para mais de uma troca
df_CRM.replace({
    "PayMethod": {1: "Cartão de Crédito", 2: "Cartão de Débito", 3: "Transferência"},
    "OrderStatus": status_pedido
}, inplace=True)

___________________
___________________

## Aprofundamento: Dados Inputados Errados

### Problemática

Dados inseridos incorretamente podem levar a análises errôneas. Podem ser erros tipográficos, valores fora de escala, entre outros.

### Resolução com .apply

A função .apply do Pandas permite aplicar uma função a cada elemento de uma coluna, o que pode ser usado para corrigir dados errados.

Suponha que uma coluna `Quantity` tenha um valores negativos, o que é claramente um erro.<br>

Suponha também que quantidades fracionadas podem ser também arredondadas.

In [ ]:
df_CRM["Quantity"].describe()

In [ ]:
def corrigir_quantidade(quantidade):
    # Verificar se a quantidade é negativa
    if quantidade < 0:
        return quantidade * -1
    else:
        return np.round(quantidade,0)

In [ ]:
# Aplicando o método apply
df_CRM["Quantity"] = df_CRM["Quantity"].apply(corrigir_quantidade)
df_CRM["Quantity"].describe()

_____
_____

## Agora é com você

Trate a base de dados `data/vendas_tech_ruim.csv` de acordo com os tópicos aprendidos nessa aula:
- Identifique as colunas que possuem dados ruins;
- Trate os dados constantes;
- Trate os dados faltantes;
- Trate os problemas de input.